version: "3"
networks:
  expense:
  driver: bridge
volumes:
  mysql-backup

services:
  mysql:
    image: chaitanyaj293/mysql:v1
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql

  backend:
    image: chaitanyaj293/backend:v1
    container_name: backend
    command: sh -c "sleep 5 && node /opt/server/index.js"
    depends_on:
      - mysql

  frontend:
    image: chaitanyaj293/frontend:v1
    container_name: frontend
    ports:
    - 80:80
    depends_on:
      - backend

